name: Development Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Linting check
        run: npm run lint

      - name: Build Next.js app
        run: npm run build

      - name: Success
        run: echo "!! Build ran successfully !!"
