name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_staging:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.NEXT_APP_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "21.1.0"

      - name: Install dependencies
        run: npm install

      - name: Lint and build code, then publish to Vercel
        run: >
          npx vercel
          --token ${{ secrets.VERCEL_TOKEN }}
          -n ${{ vars.VERCEL_PROJECT }}
          --yes
          --prod
          --env CMS_BASE_URL=${{ vars.CMS_BASE_URL }}
          --build-env CMS_BASE_URL=${{ vars.CMS_BASE_URL }}
          --env NODEMAILER_SENDER=${{ secrets.NODEMAILER_SENDER }}
          --build-env NODEMAILER_SENDER=${{ secrets.NODEMAILER_SENDER }}
          --env NODEMAILER_PASSWORD="${{ secrets.NODEMAILER_PASSWORD }}"
          --build-env NODEMAILER_PASSWORD="${{ secrets.NODEMAILER_PASSWORD }}"
          --env NODEMAILER_RECIEVER=${{ secrets.NODEMAILER_RECIEVER }}
          --build-env NODEMAILER_RECIEVER=${{ secrets.NODEMAILER_RECIEVER }}

      - name: Success
        run: echo "!! Deployment successful !!"
